### ISSUE TITLE
unhandled 'error' event

### ISSUE THREAD

**Issue by zilaijuan** [stx0821/manhuagui-autodownload#1]
我在爬“http://www.manhuagui.com/comic/8274/”的时候，碰到了这个错误。还有一点就是漫画的章节页里，章节分成了两个标签页，代码只爬了第一个标签页里的。

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.154.105.13:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

**Comment by stx0821** [comment]
manhuagui最近修改了获取图片规则，目前还在修复中

**Comment by stx0821** [comment]
已经解决多标签页问题
