### ISSUE TITLE
第一次使用是可以下载的，但是中途异常中断，然后再也无法下载

### ISSUE THREAD

**Issue by xuelainiao** [stx0821/manhuagui-autodownload#4]
求教解决办法，本人漫画迷，想下载医龙

**Comment by xuelainiao** [comment]
错误：
uncaughtException: { Error: connect ETIMEDOUT 14.49.38.185:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '14.49.38.185',
  port: 443 }
uncaughtException: { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketCloseListener (_http_client.js:363:23)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at _handle.close (net.js:557:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7) code: 'ECONNRESET' }

**Comment by stx0821** [comment]
我试了这边是可以下载的，可能是你下载频率太快，IP被暂时封了，重启下猫换个IP试试
